services:
  - type: web
    name: cardgame29
    runtime: docker
    repo: https://github.com/Md-Ruhul-Amin-Rony/CardMarriageGame
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
